// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_gate.proto

package com.gexiang.grpc;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gexiang.grpc.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>string method = 2;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string format = 3;</code>
   */
  java.lang.String getFormat();
  /**
   * <code>string format = 3;</code>
   */
  com.google.protobuf.ByteString
      getFormatBytes();

  /**
   * <code>string charset = 4;</code>
   */
  java.lang.String getCharset();
  /**
   * <code>string charset = 4;</code>
   */
  com.google.protobuf.ByteString
      getCharsetBytes();

  /**
   * <code>string sign_type = 5;</code>
   */
  java.lang.String getSignType();
  /**
   * <code>string sign_type = 5;</code>
   */
  com.google.protobuf.ByteString
      getSignTypeBytes();

  /**
   * <code>string sign = 6;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 6;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>string timestamp = 7;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 7;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string version = 8;</code>
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 8;</code>
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string app_auth_token = 9;</code>
   */
  java.lang.String getAppAuthToken();
  /**
   * <code>string app_auth_token = 9;</code>
   */
  com.google.protobuf.ByteString
      getAppAuthTokenBytes();

  /**
   * <code>string biz_content = 10;</code>
   */
  java.lang.String getBizContent();
  /**
   * <code>string biz_content = 10;</code>
   */
  com.google.protobuf.ByteString
      getBizContentBytes();
}
