// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_gate.proto

package com.gexiang.grpc;

public interface GrpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gexiang.grpc.GrpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>string sub_code = 3;</code>
   */
  java.lang.String getSubCode();
  /**
   * <code>string sub_code = 3;</code>
   */
  com.google.protobuf.ByteString
      getSubCodeBytes();

  /**
   * <code>string sub_msg = 4;</code>
   */
  java.lang.String getSubMsg();
  /**
   * <code>string sub_msg = 4;</code>
   */
  com.google.protobuf.ByteString
      getSubMsgBytes();

  /**
   * <code>string sign = 5;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 5;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();
}
