// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_gate.proto

package com.gexiang.grpc;

public final class GrpcGateProto {
  private GrpcGateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gexiang_grpc_GrpcRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gexiang_grpc_GrpcRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gexiang_grpc_GrpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gexiang_grpc_GrpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017grpc_gate.proto\022\020com.gexiang.grpc\"\300\001\n\013" +
      "GrpcRequest\022\016\n\006app_id\030\001 \001(\t\022\016\n\006method\030\002 " +
      "\001(\t\022\016\n\006format\030\003 \001(\t\022\017\n\007charset\030\004 \001(\t\022\021\n\t" +
      "sign_type\030\005 \001(\t\022\014\n\004sign\030\006 \001(\t\022\021\n\ttimesta" +
      "mp\030\007 \001(\t\022\017\n\007version\030\010 \001(\t\022\026\n\016app_auth_to" +
      "ken\030\t \001(\t\022\023\n\013biz_content\030\n \001(\t\"Z\n\014GrpcRe" +
      "sponse\022\014\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\020\n\010sub" +
      "_code\030\003 \001(\t\022\017\n\007sub_msg\030\004 \001(\t\022\014\n\004sign\030\005 \001" +
      "(\t2R\n\010GrpcGate\022F\n\005Route\022\035.com.gexiang.gr" +
      "pc.GrpcRequest\032\036.com.gexiang.grpc.GrpcRe" +
      "sponseB#\n\020com.gexiang.grpcB\rGrpcGateProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gexiang_grpc_GrpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gexiang_grpc_GrpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gexiang_grpc_GrpcRequest_descriptor,
        new java.lang.String[] { "AppId", "Method", "Format", "Charset", "SignType", "Sign", "Timestamp", "Version", "AppAuthToken", "BizContent", });
    internal_static_com_gexiang_grpc_GrpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gexiang_grpc_GrpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gexiang_grpc_GrpcResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "SubCode", "SubMsg", "Sign", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
